name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm prisma:generate
      - run: pnpm check
      - run: pnpm typecheck
